### PR TITLE
[IMP] budget_activity

### PR DESCRIPTION
**Pull request by ps-tubtim**

### CODE REVIEW

**Comment by ps-tubtim** [comment]
@kittiu @Saran440 Ready for review.

**Comment by kittiu** [comment]
Can you explain. I only see View and not Model or the base_name_search_improved will help.

**Comment by kittiu** [comment]
You will have another module later?

**Comment by kittiu** [comment]
I can't Edit, even I am Budget Manager and Admin

Selection_083

Error when save

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'group_budget_activity_tag' on model 'res.config.settings'
```

**Comment by ps-tubtim** [comment]
@kittiu I can install the module budget_activity in an empty system. You can explain the install process to me.

Peek 2021-03-19 15-08

**Comment by kittiu** [comment]
Tags shouldn't allow duplication.

Selection_084

**Comment by kittiu** [comment]
Otherwise, it is good to go.

Note: Please can you help fix the Travis? Even it is not your own, we need every help.

**Comment by kittiu** [comment]
Merged, I will fix it later.

**Pull request merged**
