### PR TITLE
[FIX] update budgeting module

### PR DESCRIPTION
**Pull request by Saran440**
- Updated module up to date.
- Fixed pre-commit `account-payment` to `account-budgeting`

### CODE REVIEW

**Comment by Saran440** [comment]
@kittiu This PR ready to merge.

**Comment by kittiu** [comment]
Still red

**Comment by kittiu** [comment]
Still wait for the cleanup.

**Comment by Saran440** [comment]
I think this PR still red because many module is not test script.
I will fix and continue implement this PR.

**Pull request merged**
